"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { ImagePlus, Loader2, Save, Upload, Video, X } from "lucide-react";

const textFields=[['name','Product name','text'],['price','Price (₹)','number'],['comparePrice','Compare price (optional)','number'],['stock','Stock','number'],['woodType','Wood type','text'],['dimensions','Dimensions','text'],['weight','Weight','text']];
export default function ProductForm({initialProduct}){
 const router=useRouter(), editing=!!initialProduct;
 const [categories,setCategories]=useState([]),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({name:initialProduct?.name||"",slug:initialProduct?.slug||"",description:initialProduct?.description||"",story:initialProduct?.story||"",price:initialProduct?.price??"",comparePrice:initialProduct?.comparePrice??"",stock:initialProduct?.stock??1,woodType:initialProduct?.woodType||"",dimensions:initialProduct?.dimensions||"",weight:initialProduct?.weight||"",careInfo:initialProduct?.careInfo||"",categoryId:initialProduct?.categoryId||"",isActive:initialProduct?.isActive??true,isFeatured:initialProduct?.isFeatured??false,isCustomizable:initialProduct?.isCustomizable??false,images:(initialProduct?.images||[]).map(x=>({url:x.url,altText:x.altText||""})),videos:(initialProduct?.videos||[]).map(x=>({url:x.url,title:x.title||""}))});
 useEffect(()=>{fetch('/api/admin/categories').then(r=>r.json()).then(d=>setCategories(d.categories||[]))},[]);
 function set(key,value){setForm(current=>({...current,[key]:value}))}
 async function upload(files,type){if(!files?.length)return;setUploading(true);setError("");for(const file of files){try{const data=new FormData();data.append('file',file);const response=await fetch(type==='video'?'/api/admin/upload/video':'/api/admin/upload',{method:'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error);setForm(current=>type==='video'?{...current,videos:[...current.videos,{url:result.url,title:current.name}]}:{...current,images:[...current.images,{url:result.url,altText:current.name}]})}catch(err){setError(err.message||'Upload failed')}}setUploading(false)}
 async function submit(e){e.preventDefault();setSaving(true);setError("");const response=await fetch(editing?`/api/admin/products/${initialProduct.id}`:'/api/admin/products',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const result=await response.json();setSaving(false);if(!response.ok)return setError(result.error||'Could not save product');router.push('/admin/products');router.refresh()}
 const input="mt-1.5 w-full rounded-xl border border-walnut/15 bg-paper px-4 py-3 text-sm outline-none focus:border-rust";
 return <form onSubmit={submit} className="space-y-7"><section className="rounded-2xl border border-walnut/10 bg-paper-warm p-5 sm:p-7"><h2 className="font-display text-lg font-semibold">Product information</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{textFields.map(([key,label,type])=><label key={key} className={key==='name'?'sm:col-span-2':''}><span className="text-sm font-medium">{label}</span><input required={['name','price','stock'].includes(key)} min={type==='number'?0:undefined} step={key.includes('price')||key==='price'?'0.01':undefined} type={type} value={form[key]} onChange={e=>set(key,e.target.value)} className={input}/></label>)}<label><span className="text-sm font-medium">Category</span><select required value={form.categoryId} onChange={e=>set('categoryId',e.target.value)} className={input}><option value="">Choose category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}{!c.isActive?' (hidden)':''}</option>)}</select></label><label><span className="text-sm font-medium">URL slug</span><input value={form.slug} onChange={e=>set('slug',e.target.value)} placeholder="Auto-generated from name" className={input}/></label></div><label className="mt-5 block"><span className="text-sm font-medium">Description</span><textarea required rows={4} value={form.description} onChange={e=>set('description',e.target.value)} className={input}/></label><label className="mt-5 block"><span className="text-sm font-medium">Craft story</span><textarea rows={3} value={form.story} onChange={e=>set('story',e.target.value)} className={input}/></label><label className="mt-5 block"><span className="text-sm font-medium">Care instructions</span><textarea rows={2} value={form.careInfo} onChange={e=>set('careInfo',e.target.value)} className={input}/></label></section>
 <section className="rounded-2xl border border-walnut/10 bg-paper-warm p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold">Photos</h2><p className="text-xs text-ink/45">First photo is the product cover.</p></div><label className="flex cursor-pointer items-center gap-2 rounded-full border border-walnut/15 px-4 py-2 text-sm font-semibold hover:bg-walnut/5"><ImagePlus size={16}/>Add photos<input hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>upload(e.target.files,'image')}/></label></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{form.images.map((image,index)=><div key={image.url} className="relative aspect-square overflow-hidden rounded-xl bg-paper"><Image src={image.url} alt={image.altText||form.name} fill className="object-cover" sizes="160px"/><button type="button" onClick={()=>set('images',form.images.filter((_,i)=>i!==index))} className="absolute right-2 top-2 rounded-full bg-black/70 p-1.5 text-white"><X size={14}/></button>{index===0&&<span className="absolute bottom-2 left-2 rounded-full bg-paper px-2 py-1 text-[10px] font-bold text-ink">Cover</span>}</div>)}</div></section>
 <section className="rounded-2xl border border-walnut/10 bg-paper-warm p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold">Product videos</h2><p className="text-xs text-ink/45">MP4, WebM or MOV, up to 100MB.</p></div><label className="flex cursor-pointer items-center gap-2 rounded-full border border-walnut/15 px-4 py-2 text-sm font-semibold hover:bg-walnut/5"><Video size={16}/>Add video<input hidden multiple type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>upload(e.target.files,'video')}/></label></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{form.videos.map((video,index)=><div key={video.url} className="relative overflow-hidden rounded-xl bg-black"><video src={video.url} controls preload="metadata" className="aspect-video w-full object-contain"/><button type="button" onClick={()=>set('videos',form.videos.filter((_,i)=>i!==index))} className="absolute right-2 top-2 rounded-full bg-black/70 p-1.5 text-white"><X size={14}/></button></div>)}</div></section>
 <section className="flex flex-wrap gap-5 rounded-2xl border border-walnut/10 bg-paper-warm p-5">{[['isActive','Visible in shop'],['isFeatured','Featured on homepage'],['isCustomizable','Customisation available']].map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form[key]} onChange={e=>set(key,e.target.checked)} className="h-4 w-4 accent-rust"/>{label}</label>)}</section>
 {uploading&&<p className="flex items-center gap-2 text-sm text-moss"><Loader2 size={16} className="animate-spin"/>Uploading media…</p>}{error&&<p className="rounded-xl bg-rust/10 p-4 text-sm text-rust">{error}</p>}<div className="flex justify-end"><button disabled={saving||uploading} className="flex items-center gap-2 rounded-full bg-rust px-7 py-3.5 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 size={17} className="animate-spin"/>:<Save size={17}/>} {editing?'Save changes':'Create product'}</button></div></form>
}
