"use client";
import { useEffect, useState } from "react";
import { Eye, EyeOff, GripVertical, Loader2, Pencil, Plus, Save, Trash2, X } from "lucide-react";

const blank = { name: "", slug: "", woodType: "", isActive: true, showOnHome: true, sortOrder: 0 };
export default function CategoriesAdminPage() {
  const [categories,setCategories]=useState([]), [editing,setEditing]=useState(null), [form,setForm]=useState(blank), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState("");
  async function load(){setLoading(true);const r=await fetch("/api/admin/categories");const d=await r.json();setCategories(d.categories||[]);setLoading(false)}
  useEffect(()=>{load()},[]);
  function edit(category){setEditing(category.id);setForm({name:category.name,slug:category.slug,woodType:category.woodType||"",isActive:category.isActive,showOnHome:category.showOnHome,sortOrder:category.sortOrder})}
  async function save(e){e.preventDefault();setSaving(true);setError("");const r=await fetch(editing?`/api/admin/categories/${editing}`:"/api/admin/categories",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setSaving(false);if(!r.ok)return setError(d.error||"Could not save category");setEditing(null);setForm(blank);load()}
  async function remove(id){if(!confirm("Delete this category? Products must be moved first."))return;const r=await fetch(`/api/admin/categories/${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)return alert(d.error);load()}
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-3xl font-semibold text-walnut">Categories</h1><p className="mt-1 text-sm text-ink/55">Control which collections appear, their order, and storefront visibility.</p></div><button onClick={()=>{setEditing(null);setForm(blank)}} className="flex items-center gap-2 rounded-full bg-rust px-5 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>New category</button></div>
    <form onSubmit={save} className="mt-7 grid gap-4 rounded-2xl border border-walnut/10 bg-paper-warm p-5 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1.5 w-full rounded-xl border border-walnut/15 bg-paper px-3 py-2.5"/></label><label className="text-sm">Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="auto-generated" className="mt-1.5 w-full rounded-xl border border-walnut/15 bg-paper px-3 py-2.5"/></label><label className="text-sm">Wood type<input value={form.woodType} onChange={e=>setForm({...form,woodType:e.target.value})} className="mt-1.5 w-full rounded-xl border border-walnut/15 bg-paper px-3 py-2.5"/></label><label className="text-sm">Display order<input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})} className="mt-1.5 w-full rounded-xl border border-walnut/15 bg-paper px-3 py-2.5"/></label><div className="flex flex-wrap items-center gap-5 sm:col-span-2 lg:col-span-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>Visible in shop</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.showOnHome} onChange={e=>setForm({...form,showOnHome:e.target.checked})}/>Show on homepage</label>{error&&<span className="text-sm text-rust">{error}</span>}</div><div className="flex justify-end gap-2"><button type="button" onClick={()=>{setEditing(null);setForm(blank)}} className="rounded-full border border-walnut/15 p-2.5"><X size={17}/></button><button disabled={saving} className="flex items-center gap-2 rounded-full bg-walnut px-5 py-2.5 text-sm font-semibold text-paper">{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Save</button></div></form>
    {loading?<p className="mt-10 text-center text-sm">Loading…</p>:<div className="mt-6 overflow-hidden rounded-2xl border border-walnut/10"><table className="w-full text-left text-sm"><thead className="bg-paper-warm text-ink/55"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Category</th><th className="hidden px-4 py-3 sm:table-cell">Products</th><th className="px-4 py-3">Visibility</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-walnut/10">{categories.map(c=><tr key={c.id}><td className="px-4 py-4"><span className="inline-flex items-center gap-1 text-ink/40"><GripVertical size={15}/>{c.sortOrder}</span></td><td className="px-4 py-4"><p className="font-semibold">{c.name}</p><p className="text-xs text-ink/45">/{c.slug}</p></td><td className="hidden px-4 py-4 sm:table-cell">{c._count?.products||0}</td><td className="px-4 py-4">{c.isActive?<span className="inline-flex items-center gap-1 text-moss"><Eye size={14}/>Shop</span>:<span className="inline-flex items-center gap-1 text-ink/40"><EyeOff size={14}/>Hidden</span>}<p className="text-xs text-ink/40">{c.showOnHome?"Homepage":"Not on home"}</p></td><td className="px-4 py-4"><div className="flex justify-end gap-1"><button onClick={()=>edit(c)} className="p-2 text-walnut"><Pencil size={16}/></button><button onClick={()=>remove(c.id)} className="p-2 text-rust"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}
  </div>
}
